name: HKJC Assistant Bot

on:
  schedule:
    # 每日香港時間 22:15 (UTC 14:15)
    - cron: '15 14 * * *'
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  TZ: Asia/Hong_Kong  # 強制系統使用香港時區

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Python script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python hkjc_tt_bot.py
