name: HKJC Bot Run

on:
  push:
    branches: [ main ]  # 當你 commit 程式碼時會自動行一次
  schedule:
    - cron: '30 15 * * *' # 每日香港時間 23:30 執行 (UTC 15:30)
  workflow_dispatch:      # 俾你喺 GitHub 網頁手動撳掣執行

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: 提取程式碼
        uses: actions/checkout@v3

      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安裝必要組件
        run: pip install requests

      - name: 執行程式
        env:
          # 這裡會讀取你之前在 GitHub Settings 設好的 Secrets
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python hkjc_tt_bot.py
